server:
  port: 8084  # ${PORT:8080}
profile: bbb
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://liaoj-eureka1.liaoj-eureka1--xufei:8761
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  sleuth:
    sampler:
      percentage: 1.0
