server:
  port: 8084  # ${PORT:8080}
profile: bbb
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.22.0.5:8748/eureka/,http://172.22.0.7:8748/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  sleuth:
    sampler:
      percentage: 1.0
